### PR TITLE
Add option --no-hash-file

### PR DESCRIPTION
**Pull request by andidev**
The alternative name for --skip-write-hash if you prefer this

### CODE REVIEW

**Comment by andidev** [comment]
Though personally I think the --no-hash-file is a bit misleading since hash file is used.

**Comment by thdk** [comment]
I have logged a new issue to implement a `package-changed check` command which I believe is what you are after. 

However I see you could use this flag already before waiting for that issue to be done so I'll merge this.

Regarding naming I am not very experienced in finding good names but I believe there is some good practice to start flags that have a `false` value with `--no-xxx`

Once there is a `--force` flag in the options list it should be clear enough what is the difference.
 
Alternative could still be to have `--no-install` to the default (install) command. But that also sounds contradictory.

**Comment by andidev** [comment]
Not sure but do you want me to do something more before you release this?

**Comment by thdk** [comment]
No I just need get to my computer, I will release it tomorrow.

Op zo 19 dec. 2021 14:35 schreef Anders Steiner ***@***.***>:

**Comment by thdk** [comment]
Released in 1.9.0

**Pull request merged**
